### ISSUE TITLE
how do you actually use this thing?

### ISSUE THREAD

**Issue by KristerV** [risul/meteor-mandrill-api#1]
Do I have to assume that the node.js way works? As in do I start the process with

```
mandrill_client = new mandrill.Mandrill('YOUR_API_KEY');
```

But then why provide the key in settings.json? please include a "getting started"

**Comment by risul** [comment]
@KristerV Very sory for late response!
Documentation is now updated... please take a look and let me know if you need more help!

**Comment by KristerV** [comment]
it's cool. I'm glad you updated.

**Comment by dandv** [comment]
@KristerV: please take a look at [wylio:mandrill](https://github.com/Wylio/meteor-mandrill), which is a faster and leaner implementation because it uses the Mandrill HTTP API directly, instead of wrapping their Node package (which does not much more than call the HTTP API itself). It also explains how to set the API key.
